# Generated by Django 3.1.3 on 2021-01-14 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gardenplus', '0002_products_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='description',
            field=models.TextField(default='This is one of the main product of our company.'),
        ),
    ]
